id = "vscode-dark-modern"
name = "VSCode Dark Modern"
version = "0.1.0"
schema_version = 1
description = "VSCode Dark Modern Theme for Zed"
repository = "https://github.com/kcamcam/vscode_dark_modern.zed"
authors = ["kcamcam <kevincamellini@gmail.com>"]
themes = ["themes/vscode-dark-modern.json"]
icon_themes = []
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
